packages:
  - packages/frontend
  - packages/tc-common

allowBuilds:
  "@parcel/watcher": false
  "@percy/core": false
  aws-sdk: true
  core-js: false
  ember-cli-image-transformer: true
  fsevents: true
  sharp: true
